####################################################
#
# Gitlab CI for automatic checks of papers and notes
# This will take care of running the needed steps
# for checking everything
#
#################################################################
#
# THIS FILE IS AUTOMATICALLY PRODUCED AND UPDATED BY THE CI TOOLS
# DON'T MODIFY THIS FILE !!!!!
#
#################################################################

image: gitlab-registry.cern.ch/atlas-physics-office/gitlab-integration/pogitlab

# Define the different stages
stages:
  - Preparation
  - Technical checks
  - ATLAS checks
  - Organize
  - Finalize
  - Build
  - Packaging


# -- VARIABLES --
variables:
  DOCNAME: ANA-TOPQ-2017-07-PAPER
  MAND_TAG: "3.0.6"
  FROZEN: newest
  IMAGE_POTL: gitlab-registry.cern.ch/atlas-physics-office/gitlab-integration/potl-2016
# -- END OF VARIABLES --

.pofilter: &pofilter
  except:
    - /^PO-.*/

.onlypo: &onlypo
  only:
    - /^PO-.*/

.version-check: &version-check
  script:
    - pogitlab --validate --doc $DOCNAME
  artifacts:
    paths:
      - gitlab-ci.yml.update
    when: on_failure


.build_template: &build_template
  stage: Build
  before_script:
    - rm -rf *.bbl *.bak *.aux .*bcf *.blg .*.lb *.fdb_latexmk *.fls
    - rm -rf *.log *.out *.run.xml *.spl *.synctex.gz *.toc *.lof *.lot *.synctex.gz
  script:
    - make BASENAME=$DOCNAME

.build_po: &build_po
  stage: Build
  before_script:
    - rm -rf *.bbl *.bak *.aux .*bcf *.blg .*.lb *.fdb_latexmk *.fls
    - rm -rf *.log *.out *.run.xml *.spl *.synctex.gz *.toc *.lof *.lot *.synctex.gz
  script:
    - cd flattened
    - make BASENAME=$DOCNAME
    - rm Makefile
    - rm -rf *.bak *.aux .*bcf *.blg .*.lb *.fdb_latexmk *.fls
    - rm -rf *.log *.out *.run.xml *.spl *.synctex.gz *.toc *.lof *.lot *.synctex.gz
  dependencies:
    - Clean Auxmat
  artifacts:
    expire_in: 1 week
    paths:
      - flattened

.texlive2016: &texlive2016
  image: gitlab-registry.cern.ch/atlas-physics-office/gitlab-integration/texlive:2016

.flat_art: &flat_art
  artifacts:
    expire_in: 1 week
    paths:
      - flattened
      - "*tar.gz"

# ######################################
# Preparation
# ######################################

Version check:
  stage: Preparation
  <<: *version-check

# ######################################
# Run needed checks for the Technical checks
# ######################################

Figures exist:
  stage: Technical checks
  allow_failure: true
  script: pogitlab --doc $DOCNAME --figs
  <<: *pofilter
  artifacts:
      paths:
          - checkFiguresExist.log
      when: on_failure

Files exist:
  stage: Technical checks
  allow_failure: true
  script: pogitlab --doc $DOCNAME --inputs
  <<: *pofilter
  artifacts:
      paths:
          - checkFiguresExist.log
      when: on_failure

Repeated commands:
  stage: Technical checks
  allow_failure: true
  script: pogitlab --doc $DOCNAME --repcommands
  <<: *pofilter
  artifacts:
      paths:
          - repeatedCommands.log
      when: on_failure

# Check for undefined references
Undefined references:
  stage: Technical checks
  script: pogitlab --doc $DOCNAME --undrefs
  allow_failure: true
  <<: *pofilter
  artifacts:
      paths:
          - checkUndefinedReferences.log
      when: on_failure

# Check for repeated labels
Repeated labels:
  stage: Technical checks
  allow_failure: true
  script: pogitlab  --doc $DOCNAME --replabels
  <<: *pofilter
  artifacts:
    paths:
        - checkRepeatedLabels.log
    when: on_failure

# Check for repeated labels
Unused labels:
  stage: Technical checks
  allow_failure: true
  script: pogitlab --doc $DOCNAME --unlabels
  <<: *pofilter
  artifacts:
    paths:
        - checkUnusedLabels.log
    when: on_failure

# ######################################
#
# Run needed checks for the ATLAS checks
#
# ######################################

# Check that the runner works for figure size
Oversized figures:
  allow_failure: true
  stage: ATLAS checks
  script: pogitlab --doc $DOCNAME --fsize
  <<: *pofilter
  artifacts:
    paths:
        - checkFiguresSize.log
    when: on_failure

# Check that the runner works for labels
Figures labels:
  stage: ATLAS checks
  allow_failure: true
  script: pogitlab --doc $DOCNAME --flabels
  <<: *pofilter
  artifacts:
    paths:
        - checkFiguresLabels.log
    when: on_failure

# Check if the runner works for template check
Template version:
  stage: ATLAS checks
  allow_failure: true
  script: pogitlab --doc $DOCNAME  --temp --frozen $FROZEN
  <<: *pofilter
  artifacts:
    paths:
        - checkTemplateVersion.log
    when: on_failure

# Check for proper cover
Cover logo:
  stage: ATLAS checks
  allow_failure: true
  script: pogitlab --doc $DOCNAME --cover
  <<: *pofilter

# Check bibliography files
Bibliography:
  stage: ATLAS checks
  allow_failure: true
  script: pogitlab --doc $DOCNAME --bib
  <<: *pofilter
  artifacts:
    paths:
        - checkBibfiles.log
    when: on_failure

# Check that the cern preprint ID
Preprint ID:
  stage: ATLAS checks
  allow_failure: true
  script: pogitlab --doc $DOCNAME --preprintid
  <<: *pofilter

# Check for new commands in Title and Abstract
Title and Abstract:
  stage: ATLAS checks
  allow_failure: true
  script: pogitlab --doc $DOCNAME --tabstract
  <<: *pofilter
  artifacts:
    paths:
        - checkNewCommands.log
    when: on_failure

# ######################################
#
# Run Build
#
# ######################################

texlive-2016:check:
  <<: *texlive2016
  <<: *build_template
  except:
    - tags
    - /PO-.*/

texlive-2016:pdf:
  <<: *texlive2016
  <<: *build_template
  when: manual
  except:
    - tags
    - /^PO-.*/
  artifacts:
    expire_in: 1 week
    paths:
      - $DOCNAME.pdf

texlive-2016:tag:
  <<: *texlive2016
  <<: *build_template
  only:
    - tags
  <<: *pofilter
  artifacts:
    expire_in: 1 week
    paths:
      - $DOCNAME.pdf

# ######################################
#
# Run checks in PO-ready
#
# ######################################

Flatten document:
  stage: Preparation
  <<: *onlypo
  script:
    - pogitlab --doc $DOCNAME --flatten
  artifacts:
    expire_in: 1 week
    paths:
      - flattened

Copy ATLAS template:
  stage: Preparation
  <<: *onlypo
  script:
    - pogitlab --doc $DOCNAME --cpsty
  artifacts:
    expire_in: 1 week
    paths:
      - flattened

Copy bibliography:
  stage: Preparation
  <<: *onlypo
  script:
    - pogitlab --doc $DOCNAME --cpbib
  artifacts:
    expire_in: 1 week
    paths:
      - flattened

Figures:
  stage: Organize
  <<: *onlypo
  script:
    - pogitlab --doc $DOCNAME --tarfigs
  artifacts:
    expire_in: 1 week
    paths:
      - flattened
      - copyFigures.log
  
Tables:
  stage: Organize
  image: $IMAGE_POTL
  <<: *onlypo
  script:
    - pogitlab --doc $DOCNAME --tartables
  artifacts:
    expire_in: 1 week
    paths:
      - flattened
      - copyTables.log

Clean Auxmat:
  stage: Finalize
  <<: *onlypo
  script:
    - pogitlab --doc $DOCNAME --flatten --avoidaux
  artifacts:
    expire_in: 1 week
    paths:
      - flattened

Publication tar:
  stage: Packaging
  <<: *onlypo
  dependencies:
    - "Build 2016"
  script:
    - cd flattened
    - rm $DOCNAME.pdf
    - tar -czvf $DOCNAME.tar.gz $(ls | grep -v .txt | grep -v tab_)
    - cd ..
    - mv flattened/$DOCNAME.tar.gz publication.tar.gz
  artifacts:
    expire_in: 1 week
    paths:
      - flattened
      - publication.tar.gz

Webpage tar:
  stage: Packaging
  <<: *onlypo
  dependencies:
    - "Build 2016"
  script:
    - cd flattened
    - rm $DOCNAME.pdf
    - tar -czvf $DOCNAME.tar.gz {tab,fig}*{txt,pdf}
    - cd ..
    - mv flattened/$DOCNAME.tar.gz webpages.tar.gz
  artifacts:
    expire_in: 1 week
    paths:
      - flattened
      - webpages.tar.gz

Build 2016:
  <<: *texlive2016
  <<: *build_po
  <<: *onlypo
